const {chromium}=require('playwright');const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const path=require('node:path');const fs=require('node:fs');
(async()=>{const server=spawn(process.execPath,['server.mjs'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,PORT:'3011'},stdio:['ignore','pipe','pipe']});let browser;try{await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(Error('server exited '+code)));});browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--disable-gpu'],headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050},locale:'ko-KR'}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://localhost:3011'))external.push(r.url());});const dir=process.env.SHOT_DIR||'/tmp/orbittrip-frames';fs.mkdirSync(dir,{recursive:true});await page.goto('http://localhost:3011');await page.waitForTimeout(500);assert.ok(await page.locator('#planner').isHidden());assert.equal(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(10, 14, 22)');await page.screenshot({path:dir+'/home.png',fullPage:true});for(let i=0;i<6;i++){await page.locator('#globe').focus();for(let k=0;k<4;k++)await page.keyboard.press('ArrowRight');await page.waitForTimeout(60);await page.locator('#globe').screenshot({path:dir+'/rotation-'+i+'.png'});}await page.locator('#globe-reset').click();await page.locator('#view-map').click();await page.waitForTimeout(100);await page.screenshot({path:dir+'/world.png',fullPage:true});await page.locator('#zoom-in').click();await page.locator('#zoom-out').click();await page.locator('#search').fill('japan');await page.locator('[data-country="JP"]').click();await page.locator('#planner').waitFor({state:'visible'});await page.locator('#load-example').click();assert.equal(await page.locator('.anchor-card').count(),4);assert.equal(await page.locator('[data-window="2026-10-13"][data-bound="start"]').inputValue(),'08:00');await page.screenshot({path:dir+'/plan.png',fullPage:true});await page.locator('#generate').click();await page.locator('#itinerary').waitFor({state:'visible'});assert.equal(await page.locator('.timeline-card').count(),1);assert.match(await page.locator('#timeline').innerText(),/디즈니랜드/);await page.locator('[data-day="3"]').click();assert.equal(await page.locator('.activity.fixed').count(),2);assert.match(await page.locator('#timeline').innerText(),/16:00/);assert.equal(await page.locator('#warnings .warning').count(),0);await page.screenshot({path:dir+'/result.png',fullPage:true});
// Compare modes without moving booked times; persist selection on reload.
const bookedBefore=await page.locator('.activity.fixed').allTextContents();
await page.locator('#result-travel-mode').selectOption('walking');
assert.deepEqual(await page.locator('.activity.fixed').allTextContents(),bookedBefore);
assert.ok(await page.locator('#dirty-notice').isVisible());
await page.locator('.route-leg summary').first().click();
assert.match(await page.locator('.route-detail').first().innerText(),/좌표 거리 기반 추정/);
await page.reload();await page.locator('#resume').click();
assert.equal(await page.locator('#result-travel-mode').inputValue(),'walking');
await page.locator('#result-travel-mode').selectOption('driving');
assert.match(await page.locator('.route-leg summary').first().innerText(),/자동차/);
await page.locator('#result-travel-mode').selectOption('transit');
// Edit an exact booking, regenerate, preserve it and fill around it.
await page.locator('#back-plan').click();await page.locator('.anchor-card').filter({hasText:'팀랩'}).locator('[data-edit-visit]').click();await page.locator('#visit-start').fill('16:30');await page.locator('#visit-end').fill('18:30');await page.locator('#visit-form button[type=submit]').click();await page.locator('#generate').click();await page.locator('[data-day="3"]').click();assert.match(await page.locator('.activity.fixed').filter({hasText:'팀랩'}).locator('..').innerText(),/16:30/);await page.locator('[data-delete]').first().click();const n=await page.locator('.timeline-card').count();await page.reload();await page.locator('#resume').click();assert.equal(await page.locator('.timeline-card').count(),n);
// Add a new exact booking through the form rather than just a seeded example.
await page.locator('#back-plan').click();await page.locator('#add-visit').click();await page.locator('#visit-date').selectOption('2026-10-14');await page.locator('#visit-place').selectOption('도쿄6');await page.locator('#visit-mode').selectOption('morning');await page.locator('#visit-form button[type=submit]').click();assert.equal(await page.locator('.anchor-card').count(),5);await page.locator('#generate').click();await page.locator('[data-day="2"]').click();assert.match(await page.locator('.activity.fixed').innerText(),/메이지/);
// Invalid overlap blocks generation and keeps the last valid plan.
await page.locator('#back-plan').click();await page.locator('.anchor-card').filter({hasText:'팀랩'}).locator('[data-edit-visit]').click();await page.locator('#visit-start').fill('14:00');await page.locator('#visit-form button[type=submit]').click();await page.locator('#generate').click();assert.ok(await page.locator('#form-error').isVisible());assert.match(await page.locator('#form-error').innerText(),/겹칩니다/);await page.locator('.anchor-card').filter({hasText:'팀랩'}).locator('[data-edit-visit]').click();await page.locator('#visit-start').fill('16:30');await page.locator('#visit-form button[type=submit]').click();
// Mobile layout across all three stages and both globe/map.
await page.setViewportSize({width:390,height:844});await page.screenshot({path:dir+'/mobile-plan.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#generate').click();await page.locator('[data-day="3"]').click();await page.screenshot({path:dir+'/mobile-result.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#home').click();await page.locator('#view-globe').click();await page.waitForTimeout(100);await page.screenshot({path:dir+'/mobile-home.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#view-map').click();await page.screenshot({path:dir+'/mobile-world.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
// Country switching preserves each country's draft.
await page.locator('#search').fill('France');await page.locator('[data-country="FR"]').click();await page.locator('#planner').waitFor({state:'visible'});assert.match(await page.locator('#selected-country').innerText(),/프랑스/);await page.locator('#generate').click();assert.ok(await page.locator('#result').isVisible());await page.locator('#home').click();await page.locator('#search').fill('Japan');await page.locator('[data-country="JP"]').click();await page.locator('#planner').waitFor({state:'visible'});assert.equal(await page.locator('.anchor-card').count(),5);await page.locator('#home').click();await page.locator('#search').fill('Thailand');await page.locator('[data-country="TH"]').click();await page.locator('#planner').waitFor({state:'visible'});await page.locator('#generate').click();assert.match(await page.locator('#day-title').innerText(),/방콕/);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS: real Chromium desktop/mobile; globe rotation, map/zoom, staged navigation, fixed visits, recommended windows, editing, regeneration, conflicts, reload persistence, per-country drafts; zero JS errors and zero external requests.');}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exit(1)});
