import test from 'node:test';
import assert from 'node:assert/strict';
import {createGeo} from '../geo.mjs';
import {rememberRoute} from '../public/route-cache.js';
import {travel,routeEstimate,warnings,generate,station} from '../public/engine.js';
async function request(handle,path){let result;const res={writeHead(status,headers){result={status,headers};},end(body){result.body=body;}};await handle({method:'GET'},res,new URL(path,'http://localhost'),(status,body)=>result={status,body});return result;}
test('Geo status is safe, missing keys do not fetch, invalid input and transit are rejected',async()=>{let called=0;const h=createGeo({key:'',fetcher:()=>called++});assert.deepEqual((await request(h,'/api/geo/status')).body,{enabled:false,provider:'Geoapify',modes:['driving','walking']});assert.equal((await request(h,'/api/geo/places?lat=35&lng=139&radius=15000')).status,503);assert.equal((await request(h,'/api/geo/places?lat=&lng=139&radius=15000')).status,400);assert.equal((await request(h,'/api/geo/route?fromLat=35&fromLng=139&toLat=36&toLng=140&mode=transit')).status,422);assert.equal((await request(h,'/api/geo/tiles/99/0/0.png')).status,400);assert.equal(called,0);});
test('Places normalize coordinates, cache identical requests and never expose upstream key or raw fields',async()=>{let calls=0;const h=createGeo({key:'server-secret',fetcher:async url=>{calls++;assert.equal(new URL(url).hostname,'api.geoapify.com');return {ok:true,json:async()=>({features:[{properties:{place_id:'abc',name:'Museum',lat:35,lon:139,formatted:'Tokyo',raw:'server-secret'}}]})};}});const path='/api/geo/places?lat=35&lng=139&radius=15000';const a=await request(h,path),b=await request(h,path);assert.equal(calls,1);assert.deepEqual(a,b);assert.equal(a.body.places[0].lng,139);assert.equal(a.body.places[0].source,'geoapify');assert.ok(!JSON.stringify(a).includes('server-secret'));});
test('Road route returned with geometry and instructions; upstream errors are sanitized',async()=>{const h=createGeo({key:'secret',fetcher:async()=>({ok:true,json:async()=>({features:[{properties:{time:125,distance:1000,legs:[{steps:[{instruction:{text:'Turn left'}}]}]},geometry:{type:'LineString',coordinates:[[139,35],[139.01,35.01]]}}]})})});const a=await request(h,'/api/geo/route?fromLat=35&fromLng=139&toLat=35.01&toLng=139.01&mode=walking');assert.equal(a.body.minutes,3);assert.equal(a.body.distanceKm,1);assert.deepEqual(a.body.steps,['Turn left']);const bad=createGeo({key:'secret',fetcher:async()=>{throw Error('https://api.geoapify.com?apiKey=secret');}});const r=await request(bad,'/api/geo/places?lat=35&lng=139&radius=15000');assert.equal(r.status,503);assert.ok(!JSON.stringify(r).includes('secret'));});
test('Fetched route minutes affect planning warnings without modifying booked times',()=>{const a=station('도쿄'),b={lat:a.lat+.02,lng:a.lng+.02,name:'Booked museum',city:'도쿄',start:'09:15',end:'10:00',locked:true,buffer:0};rememberRoute(a,b,'walking',{minutes:40,distanceKm:2,source:'geoapify',steps:[],notice:'test'});assert.equal(travel(a,b,'walking'),40);assert.equal(routeEstimate(a,b,'transit').source,'offline-estimate');const day={city:'도쿄',window:{start:'09:00',end:'20:00'},travelMode:'walking',items:[b]};assert.ok(warnings(day).some(s=>s.includes('25분 부족')));assert.equal(b.start,'09:15');});
test('External candidates are used by the recommendation engine',()=>{const city='도쿄',a=station(city),external={...a,id:'external-museum-test',name:'External nearest museum',duration:60,type:'관광'};const plan=generate({start:'2026-10-12',end:'2026-10-12',cities:[city],pace:'slow',travelMode:'driving',windows:{},visits:[],fixed:[],externalPlaces:[external]});assert.ok(plan[0].items.some(p=>p.id===external.id));});
