import test from 'node:test';
import assert from 'node:assert/strict';
import {generate,validate,warnings,minute,travel,endPoint,freeGaps,logisticsFor} from '../public/engine.js';
import {prepareRecommendations} from '../public/recommendation-data.js';
const hotel=(id,from,to,lat=35.713,lng=139.775)=>({id,name:id,city:'도쿄',lat,lng,from,to,checkin:'15:00',checkout:'11:00',checkinDuration:30,checkoutDuration:20});
const base=()=>({start:'2026-10-12',end:'2026-10-16',cities:Array(5).fill('도쿄'),windows:{},fixed:[],visits:[],pace:'normal',travelMode:'transit',stays:[hotel('우에노 숙소','2026-10-12','2026-10-16')],flights:{arrival:{name:'하네다 공항',city:'도쿄',lat:35.5494,lng:139.7798,time:'17:00',buffer:60,outboundTime:'15:00'},departure:{name:'하네다 공항',city:'도쿄',lat:35.5494,lng:139.7798,time:'17:00',buffer:180}}});
test('arrival 17:00 clears immigration at 18:00; hotel check-in precedes all sightseeing',()=>{const c=base(),days=generate(c),d=days[0];assert.equal(d.origin.name,'하네다 공항');assert.equal(d.items[0].kind,'arrival');assert.equal(d.items[0].end,'18:00');assert.equal(d.items[1].kind,'checkin');assert.ok(minute(d.items[1].start)>=1080+travel(c.flights.arrival,c.stays[0],c.travelMode));assert.ok(d.items.filter(p=>!p.locked).every(p=>minute(p.start)>=minute(d.items[1].end)));for(const day of days)assert.deepEqual(warnings(day),[]);assert.ok(days.slice(1,-1).every(d=>d.origin.name==='우에노 숙소'&&d.destination.name==='우에노 숙소'));});
test('departure reserves airport arrival by 14:00 and never adds sightseeing after flight',()=>{const c=base(),d=generate(c).at(-1),flight=d.items.at(-1);assert.equal(flight.kind,'departure');assert.equal(flight.start,'14:00');assert.equal(flight.end,'17:00');const prev=d.items.at(-2);assert.ok(minute(prev.end)+travel(endPoint(prev),flight,c.travelMode)<=840);assert.equal(d.destination,null);assert.deepEqual(warnings(d),[]);assert.ok(freeGaps(d).every(g=>minute(g.end)<=840));});
test('hotel change uses old lodging as origin and new lodging as return with checkout and checkin',()=>{const c=base();c.stays=[hotel('A','2026-10-12','2026-10-14'),hotel('B','2026-10-14','2026-10-16',35.6595,139.7005)];const ds=generate(c),d=ds[2];assert.equal(d.origin.name,'A');assert.equal(d.destination.name,'B');assert.ok(d.items.some(p=>p.kind==='checkout'));assert.ok(d.items.some(p=>p.kind==='checkin'));assert.equal(ds[3].origin.name,'B');assert.deepEqual(warnings(d),[]);});
test('overlap, missed checkout, impossible airport connection and overnight processing are rejected',()=>{let c=base();c.stays.push(hotel('B','2026-10-13','2026-10-16'));assert.throws(()=>validate(c),/겹칩니다/);c=base();c.windows[c.end]={start:'11:00',end:'20:00'};assert.throws(()=>validate(c),/체크아웃 마감/);c=base();c.flights.departure.time='03:00';assert.throws(()=>validate(c),/활동|시간/);c=base();c.flights.arrival.time='23:30';assert.throws(()=>validate(c),/자정/);});
test('manual edits warn about insufficient hotel return time',()=>{const d=generate(base())[1],p=d.items.at(-1);p.end=d.window.end;assert.ok(warnings(d).some(v=>v.includes('숙소')));});
test('city expansion searches around lodging, is capped and reuses selected places',async()=>{const c=base(),urls=[];const out=await prepareRecommendations(c,()=>{},{expandCity:'도쿄',fetcher:async url=>{urls.push(url);return {ok:true,json:async()=>url.includes('status')?{enabled:true}:{places:[{id:'extra',name:'새 장소',lat:35.71,lng:139.77,duration:60,type:'관광'}]}};}});assert.ok(out.places.some(p=>p.id==='extra'));assert.ok(urls.length<=9);const query=new URL(urls[1],'http://local').searchParams;assert.equal(query.get('lat'),String(c.stays[0].lat));});

test('early departure advances hotel checkout and late arrival leaves no invented sightseeing',()=>{const c=base();c.flights.departure.time='09:00';let d=generate(c).at(-1);assert.ok(minute(d.window.start)<360);assert.equal(d.items.at(-1).start,'06:00');assert.deepEqual(warnings(d),[]);c.flights.arrival.time='21:00';d=generate(c)[0];assert.equal(d.items.filter(p=>!p.locked).length,0);assert.deepEqual(warnings(d),[]);});

test('changing cities requires booked transport and carries new hotel into the next day',()=>{const c=base();delete c.flights.departure;c.cities=['도쿄','도쿄','도쿄','교토','교토'];c.stays=[hotel('Tokyo','2026-10-12','2026-10-14'),{...hotel('Kyoto','2026-10-14','2026-10-16',34.9858,135.7588),city:'교토'}];assert.throws(()=>validate(c),/도시/);c.fixed=[{id:'train',date:'2026-10-14',from:'도쿄',to:'교토',name:'예약 기차',start:'12:00',end:'14:15'}];const ds=generate(c);assert.equal(ds[2].destination.city,'교토');assert.equal(ds[3].origin.city,'교토');assert.deepEqual(warnings(ds[2]),[]);});
