import test from 'node:test';
import assert from 'node:assert/strict';
import {generate,validate,warnings,dates,minute,travel,freeGaps} from '../public/engine.js';
import {dateTime} from '../public/overnight.js';
const airport={name:'하네다',city:'도쿄',lat:35.5494,lng:139.7798};
const base=()=>({start:'2026-12-31',end:'2027-01-04',cities:Array(5).fill('도쿄'),windows:{},fixed:[],visits:[],travelMode:'transit',pace:'normal',stays:[{id:'hotel',name:'숙소',city:'도쿄',lat:35.713,lng:139.775,from:'2026-12-31',to:'2027-01-04',checkin:'15:00',checkout:'11:00',checkinDuration:30,checkoutDuration:20}],flights:{arrival:{...airport,time:'23:30',buffer:60},departure:{...airport,time:'01:00',buffer:180}}});
const check=c=>{const plan=generate(c);assert.deepEqual(plan.flatMap(warnings),[]);for(const d of plan)for(const p of d.items){assert.equal(p.startDateTime,dateTime(d.date,minute(p.start)));assert.equal(p.endDateTime,dateTime(d.date,minute(p.end)));assert.ok(p.startDateTime<p.endDateTime);}return plan;};
test('year boundary arrival, baggage, transfer and check-in continue on next date; sightseeing waits until activity start',()=>{const plan=check(base());assert.equal(plan[0].items[0].endDateTime,'2027-01-01T00:00');assert.equal(plan[1].items[0].end,'00:30');assert.equal(plan[1].items[1].kind,'transfer');assert.equal(plan[1].items[2].kind,'checkin');assert.ok(plan[1].items.filter(p=>!p.locked).every(p=>minute(p.start)>=540));assert.equal(plan[2].origin.name,'숙소');});
test('check-in alone straddles midnight, including exact midnight completion',()=>{for(const duration of [30,45]){const c=base();c.flights.arrival.time='22:00';c.flights.arrival.buffer=15;c.stays[0].checkin='23:30';c.stays[0].checkinDuration=duration;const p=check(c);assert.equal(p[0].items.at(-1).kind,'checkin');assert.equal(p[0].items.at(-1).end,'24:00');if(duration===45)assert.equal(p[1].items[0].end,'00:15');}});
test('airport transfer across midnight reserves both date portions exactly once',()=>{const c=base();c.flights.arrival.time='22:45';c.flights.arrival.buffer=30;const plan=check(c),chunks=plan.flatMap(d=>d.items).filter(p=>p.kind==='transfer');assert.equal(chunks.length,3);const arrivalChunks=chunks.filter(p=>p.note.includes('2026-12-31'));assert.equal(arrivalChunks.length,2);assert.equal(arrivalChunks.reduce((n,p)=>n+minute(p.end)-minute(p.start),0),travel(airport,c.stays[0],c.travelMode));});
test('early flight puts checkout, transfer and departure processing on previous date',()=>{const c=base(),p=check(c);assert.deepEqual(p[3].items.filter(p=>p.locked).map(p=>p.kind),['checkout','transfer','departure']);assert.equal(p[3].items.at(-1).endDateTime,p[4].items[0].startDateTime);assert.equal(p[4].items[0].end,'01:00');assert.ok(freeGaps(p[4]).length===0);});
test('checkout itself can cross midnight before airport transfer',()=>{const c=base();c.flights.departure.time='02:20';c.flights.departure.buffer=60;c.stays[0].checkoutDuration=30;const p=check(c);assert.equal(p[3].items.at(-1).kind,'checkout');assert.equal(p[4].items[0].kind,'checkout');assert.equal(p[4].items[0].end,'00:20');});
test('midnight departure finishes entirely on previous date',()=>{const c=base();c.flights.departure.time='00:00';const p=check(c);assert.equal(p[4].items.length,0);assert.equal(p[3].items.at(-1).endDateTime,'2027-01-04T00:00');});
test('no hotel still carries immigration and airport processing across dates',()=>{const c=base();c.stays=[];const p=check(c);assert.equal(p[1].items[0].kind,'arrival');assert.equal(p[4].items[0].kind,'departure');});
test('travel period overflow and booking overlap are blocked without moving reservations',()=>{const c=base();c.end=c.start;c.cities=['도쿄'];c.stays=[];delete c.flights.departure;assert.throws(()=>validate(c),/여행 기간/);const d=base();d.visits=[{id:'v',date:'2027-01-01',name:'예약',city:'도쿄',lat:35.713,lng:139.775,start:'00:45',end:'01:00'}];assert.throws(()=>validate(d),/겹칩니다|부족/);assert.equal(d.visits[0].start,'00:45');});
test('same day v2 data and JSON round trip keep input and existing plans compatible',()=>{const c=base();c.flights.arrival.time='17:00';c.flights.departure.time='17:00';const before=JSON.stringify(c),p=check(c);assert.equal(JSON.stringify(c),before);assert.equal(p[0].items[1].kind,'checkin');assert.equal(p.at(-1).items.at(-1).start,'14:00');const stored=JSON.parse(JSON.stringify({version:2,state:{...c,plan:p}}));assert.deepEqual(generate(stored.state),p);});
test('90-day plan preserves all dates and train arrival carry with overnight endpoints',()=>{const c=base();c.end='2027-03-30';c.cities=Array(90).fill('도쿄');c.stays[0].to='2027-01-02';c.stays.push({...c.stays[0],id:'kyoto',name:'교토 숙소',city:'교토',lat:34.9858,lng:135.7588,from:'2027-01-02',to:c.end});c.cities=c.cities.map((v,i)=>i>=3?'교토':v);c.fixed=[{id:'train',date:'2027-01-02',from:'도쿄',to:'교토',name:'예약 기차',start:'12:00',end:'14:15'}];c.flights.departure={...c.flights.departure,city:'교토',lat:34.78,lng:135.43};const p=check(c);assert.equal(p[2].items.find(p=>p.kind==='transport').end,'14:15');assert.equal(p[3].origin.city,'교토');assert.equal(p.length,90);assert.equal(p.at(-1).date,c.end);assert.equal(dates(c.start,c.end).length,90);});
test('ordinary overnight visits and malformed flight times remain rejected',()=>{const c=base();c.visits=[{id:'v',date:c.start,name:'예약',city:'도쿄',lat:35.7,lng:139.7,start:'23:00',end:'01:00'}];assert.throws(()=>validate(c),/시간/);c.visits=[];c.flights.arrival.time='24:00';assert.throws(()=>validate(c),/항공편/);});
test('hotel-only check-in at midnight continues in next date',()=>{const c=base();c.flights={};c.stays[0].checkin='23:45';const p=check(c);assert.equal(p[0].items.at(-1).kind,'checkin');assert.equal(p[1].items[0].end,'00:15');});

test('a longer transport mode warns without moving locked midnight segments',()=>{const c=base(),p=check(c)[1],times=p.items.map(p=>[p.start,p.end]);p.travelMode='walking';assert.ok(warnings(p).some(s=>s.includes('다시 추천')));assert.deepEqual(p.items.map(p=>[p.start,p.end]),times);});


test('airport transfer ending exactly at midnight carries airport origin into departure date',()=>{const c=base();c.flights.departure.time='03:00';const p=check(c);assert.equal(p[3].items.at(-1).kind,'transfer');assert.equal(p[4].origin.lat,airport.lat);assert.equal(p[4].items[0].start,'00:00');});
