import test from 'node:test';import assert from 'node:assert/strict';
import {generate,warnings,distance,station,routeEstimate} from '../public/engine.js';
import {places,stations} from '../public/data.js';
import {prepareRecommendations} from '../public/recommendation-data.js';
const base=()=>({start:'2026-10-12',end:'2026-10-16',cities:Array(5).fill('도쿄'),pace:'normal',travelMode:'transit',visits:[],fixed:[],windows:{}});
test('Tokyo five days remain populated; Ueno and Ameyoko stay together and consecutive',()=>{const plan=generate(base());assert.deepEqual(plan.map(d=>d.items.length),[5,5,5,5,5]);const ueno=plan.findIndex(d=>d.items.some(p=>p.name==='우에노 공원')),market=plan.findIndex(d=>d.items.some(p=>p.name==='아메요코 시장'));assert.equal(ueno,market);const stops=plan[ueno].items;assert.equal(Math.abs(stops.findIndex(p=>p.name==='우에노 공원')-stops.findIndex(p=>p.name==='아메요코 시장')),1);assert.deepEqual(plan.flatMap(warnings),[]);assert.equal(new Set(plan.flatMap(d=>d.items.map(p=>p.id))).size,25);assert.ok(plan.every(d=>new Set(d.items.map(p=>p.area)).size===1));});
test('Nearby attractions no longer require cross-city backtracking inside a day',()=>{const p=generate(base());for(const day of p){for(let i=1;i<day.items.length;i++)assert.ok(distance(day.items[i-1],day.items[i])<3.5,day.items.map(p=>p.name).join('→'));}const towerDay=p.find(d=>d.items.some(p=>p.id==='tokyo-tower'));assert.equal(Math.abs(towerDay.items.findIndex(p=>p.id==='tokyo-tower')-towerDay.items.findIndex(p=>p.id==='tokyo-zojoji')),1);});
test('A future Ueno reservation keeps nearby Ameyoko on that date and preserves the reservation',()=>{const c=base(),p=places.find(p=>p.id==='도쿄3');c.visits=[{...p,id:'reservation',placeId:p.id,date:'2026-10-15',start:'13:00',end:'14:30',buffer:15}];const plan=generate(c),market=plan.find(d=>d.items.some(p=>p.id==='도쿄4'));assert.equal(market.date,'2026-10-15');assert.equal(plan[3].items.find(p=>p.locked).start,'13:00');assert.deepEqual(plan.flatMap(warnings),[]);});
test('Sparse data is spread over days, failures stay honest instead of inventing places',async()=>{const city=Object.keys(stations).find(k=>!places.some(p=>p.city===k)),c={...base(),cities:Array(5).fill(city)};const a=station(city);c.externalPlaces=Array.from({length:10},(_,i)=>({...a,id:'spread-'+i,name:'Candidate '+i,lat:a.lat+i*.001,type:'관광',duration:60}));const p=generate(c);assert.ok(p.every(d=>d.items.length>=1));const unavailable=await prepareRecommendations({...c,externalPlaces:[]},()=>{},{fetcher:async()=>({ok:true,json:async()=>({enabled:false})})});assert.ok(unavailable.notices.length);assert.equal(generate({...c,externalPlaces:unavailable.places}).flatMap(d=>d.items).length,0);});
test('Sufficient Tokyo data needs no API; short catalogs automatically retrieve bounded candidates',async()=>{let calls=0;await prepareRecommendations(base(),()=>{},{fetcher:async()=>{calls++;throw Error();}});assert.equal(calls,0);const city=Object.keys(stations).find(k=>!places.some(p=>p.city===k)),a=station(city);const result=await prepareRecommendations({...base(),cities:Array(5).fill(city)},()=>{},{fetcher:async url=>{calls++;return {ok:true,json:async()=>url.endsWith('/status')?{enabled:true}:{places:Array.from({length:30},(_,i)=>({...a,id:'remote-'+i,name:'Real API place '+i,lat:a.lat+i*.002,lng:a.lng+i*.002,duration:60,type:'관광',source:'geoapify'}))}};}});assert.ok(result.places.length>=25);assert.ok(calls<=9);assert.ok(generate({...base(),cities:Array(5).fill(city),externalPlaces:result.places}).every(d=>d.items.length));});

test('Short transit legs use a walking connection rather than a notional train ride',()=>{const a=places.find(p=>p.name==='아키하바라'),b=places.find(p=>p.name==='아메요코 시장');assert.match(routeEstimate(a,b,'transit').method,/도보/);});
